apiVersion: v2
name: red-app
description: RED Risk Management Platform - On-Premise Helm Chart
type: application
version: 0.1.0
appVersion: "v1.0.0"
home: https://redrisk.eu
maintainers:
  - name: RED Team
    email: support@redrisk.eu
keywords:
  - risk-management
  - grc
  - compliance
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
